CREATE TABLE [dbo].[POSTAVA] (
    [PREDID]       INT          NOT NULL,
    [GLUMID]       INT          NOT NULL,
    [NAZIV_SEZONE] VARCHAR (10) NOT NULL,
    [ULOGA]        VARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([GLUMID] ASC, [PREDID] ASC, [NAZIV_SEZONE] ASC),
    FOREIGN KEY ([NAZIV_SEZONE]) REFERENCES [dbo].[SEZONA] ([NAZIV_SEZONE]),
    FOREIGN KEY ([GLUMID]) REFERENCES [dbo].[GLUMAC] ([GLUMID]),
    FOREIGN KEY ([PREDID]) REFERENCES [dbo].[PREDSTAVA] ([PREDID])
);

