CREATE TABLE [dbo].[PREDSTAVA] (
    [PREDID] INT          NOT NULL,
    [NAZIV]  VARCHAR (50) NULL,
    [TIP]    VARCHAR (10) NULL,
    PRIMARY KEY CLUSTERED ([PREDID] ASC),
    CONSTRAINT [CK_PREDSTAVA_TIP] CHECK ([TIP]='TRAGEDIJA' OR [TIP]='DRAMA' OR [TIP]='KOMEDIJA')
);

