CREATE TABLE [dbo].[REPERTOAR] (
    [PREDID]      INT          NOT NULL,
    [DATUMIVREME] DATETIME     NOT NULL,
    [STATUS]      VARCHAR (10) NULL,
    PRIMARY KEY CLUSTERED ([PREDID] ASC, [DATUMIVREME] ASC),
    FOREIGN KEY ([PREDID]) REFERENCES [dbo].[PREDSTAVA] ([PREDID]),
    CONSTRAINT [CK_REPERTOAR_STATUS] CHECK ([STATUS]='OTKAZANA' OR [STATUS]='ODIGRANA')
);

