INSERT into dbo.GLUMAC (GLUMID,IME,PREZIME)
VALUES (1,'Mira','Stupica'),
(2,'Milena','Dravic'),
(3,'Olivera','Markovic'),
(4,'Radmila','Savicevic'),
(5,'Mira','Banjac'),
(6,'Ruzica','Sokic'),
(7,'Seka','Sablic'),
(8,'Svetlana','Bojkovic'),
(9,'Tanja','Boskovic'),
(10,'Neda','Arneric'),
(11,'Zoran','Radmilovic'),
(12,'Pavle','Vuisic'),
(13,'Aleksandar','Bercek'),
(14,'Mija','Aleksic'),
(15,'Miodrag','Ckalja'),
(16,'Velimir','Zivojinovic'),
(17,'Ljuba','Tadic'),
(18,'Petar','Kralj'),
(19,'Danilo','Stojkovic'),
(20,'Dragan','Nikolic')